name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install repo2docker
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-repo2docker

    - name: Build and push Docker image to Binder cache and Docker Hub
      env:
        MYBINDERORG_CACHE: true
      run: |
        jupyter-repo2docker --no-run --user-name jovyan --user-id 1000 --image-name savasceylan/seismo_at_school .
        docker build -t savasceylan/seismo_at_school:latest .
        docker push savasceylan/seismo_at_school:latest
