name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      env:
        MYBINDERORG_CACHE: true
      run: |
        IMAGE_TAG="distribution"
        # Build the Docker image locally from the Dockerfile
        docker build -t seismoatschool/seismo_at_school:$IMAGE_TAG .
        # Push the Docker image to Docker Hub
        docker push seismoatschool/seismo_at_school:$IMAGE_TAG
